// Mock data for Kerala real estate - Pala, Erattupetta, Kottayam region

export const mockProperties = [
  {
    id: '1',
    slug: 'luxury-villa-pala-town',
    title: '4BHK Luxury Villa in Pala Town',
    description: 'Stunning contemporary villa with modern amenities, spacious rooms, and beautiful garden. Located in prime residential area of Pala with easy access to schools, hospitals, and shopping centers. Perfect for families seeking comfort and convenience.',
    price: 12500000,
    priceLabel: '₹1.25 Cr',
    type: 'villa',
    status: 'available',
    featured: true,
    bedrooms: 4,
    bathrooms: 4,
    sqftSuperBuiltUp: 2800,
    sqftCarpet: 2200,
    yearBuilt: 2023,
    parking: 2,
    furnishingStatus: 'semi-furnished',
    reraNumber: 'K-RERA-1-440-2023-HP-220156',
    location: {
      address: 'Near St. Thomas Church, Pala Town',
      city: 'Pala',
      district: 'Kottayam',
      state: 'Kerala',
      pincode: '686575',
      latitude: 9.7167,
      longitude: 76.6833,
    },
    amenities: [
      { item: 'Modular Kitchen' },
      { item: 'Solar Water Heater' },
      { item: 'Rainwater Harvesting' },
      { item: 'Compound Wall' },
      { item: 'Power Backup' },
      { item: 'Bore Well' },
    ],
    gallery: [
      { image: { url: 'https://picsum.photos/id/1018/1200/800' } },
      { image: { url: 'https://picsum.photos/id/1019/1200/800' } },
      { image: { url: 'https://picsum.photos/id/1024/1200/800' } },
    ],
  },
  {
    id: '2',
    slug: 'apartment-mc-road-kottayam',
    title: '3BHK Apartment on MC Road Kottayam',
    description: 'Premium apartment in the heart of Kottayam city on MC Road. Excellent connectivity to railway station, bus stand, and all major landmarks. Modern amenities with 24/7 security. Ideal for professionals and families.',
    price: 8500000,
    priceLabel: '₹85 Lakhs',
    type: 'apartment',
    status: 'available',
    featured: true,
    bedrooms: 3,
    bathrooms: 3,
    sqftSuperBuiltUp: 1650,
    sqftCarpet: 1350,
    yearBuilt: 2024,
    parking: 2,
    furnishingStatus: 'fully-furnished',
    reraNumber: 'K-RERA-1-440-2024-HP-220189',
    location: {
      address: 'MC Road, Near CMS College',
      city: 'Kottayam',
      district: 'Kottayam',
      state: 'Kerala',
      pincode: '686001',
      latitude: 9.5916,
      longitude: 76.5222,
    },
    amenities: [
      { item: 'Lift' },
      { item: 'Gym' },
      { item: 'Covered Parking' },
      { item: '24/7 Security' },
      { item: 'Power Backup' },
      { item: 'Intercom' },
    ],
    gallery: [
      { image: { url: 'https://picsum.photos/id/1027/1200/800' } },
      { image: { url: 'https://picsum.photos/id/1029/1200/800' } },
    ],
  },
  {
    id: '3',
    slug: 'heritage-home-erattupetta',
    title: 'Traditional Kerala Home in Erattupetta',
    description: 'Beautiful traditional Kerala style house with modern upgrades. Spacious rooms with wooden interiors, large courtyard, and mature garden. Peaceful location with scenic views of rubber plantations. Perfect blend of tradition and comfort.',
    price: 9500000,
    priceLabel: '₹95 Lakhs',
    type: 'independent-house',
    status: 'available',
    featured: true,
    bedrooms: 4,
    bathrooms: 3,
    sqftSuperBuiltUp: 2400,
    sqftCarpet: 2000,
    yearBuilt: 2020,
    parking: 2,
    furnishingStatus: 'semi-furnished',
    reraNumber: 'K-RERA-1-440-2020-HP-220134',
    location: {
      address: 'Erattupetta Town, Near Govt Hospital',
      city: 'Erattupetta',
      district: 'Kottayam',
      state: 'Kerala',
      pincode: '686121',
      latitude: 9.6869,
      longitude: 76.7769,
    },
    amenities: [
      { item: 'Traditional Architecture' },
      { item: 'Wooden Interiors' },
      { item: 'Large Courtyard' },
      { item: 'Bore Well' },
      { item: 'Solar Panels' },
      { item: 'Fruit Trees' },
    ],
    gallery: [
      { image: { url: 'https://picsum.photos/id/1036/1200/800' } },
      { image: { url: 'https://picsum.photos/id/1039/1200/800' } },
    ],
  },
  {
    id: '4',
    slug: 'modern-villa-pala-bypass',
    title: 'Contemporary Villa near Pala Bypass',
    description: 'Ultra-modern 5BHK villa with premium finishes and smart home features. Spacious layout with separate living and dining areas, home theater room, and landscaped garden. Located in gated community with excellent security.',
    price: 15000000,
    priceLabel: '₹1.5 Cr',
    type: 'villa',
    status: 'available',
    featured: false,
    bedrooms: 5,
    bathrooms: 5,
    sqftSuperBuiltUp: 3500,
    sqftCarpet: 2900,
    yearBuilt: 2024,
    parking: 3,
    furnishingStatus: 'fully-furnished',
    reraNumber: 'K-RERA-1-440-2024-HP-220201',
    location: {
      address: 'Pala Bypass Road, Green Valley',
      city: 'Pala',
      district: 'Kottayam',
      state: 'Kerala',
      pincode: '686575',
      latitude: 9.7200,
      longitude: 76.6900,
    },
    amenities: [
      { item: 'Smart Home System' },
      { item: 'Home Theater' },
      { item: 'Swimming Pool' },
      { item: 'Landscaped Garden' },
      { item: 'Security System' },
      { item: 'Generator' },
    ],
    gallery: [
      { image: { url: 'https://picsum.photos/id/1041/1200/800' } },
    ],
  },
  {
    id: '5',
    slug: 'budget-apartment-kottayam',
    title: '2BHK Budget Apartment in Kottayam',
    description: 'Affordable apartment perfect for small families and first-time buyers. Well-maintained building with basic amenities. Good connectivity to schools, markets, and public transport. Value for money property in prime location.',
    price: 4500000,
    priceLabel: '₹45 Lakhs',
    type: 'apartment',
    status: 'available',
    featured: false,
    bedrooms: 2,
    bathrooms: 2,
    sqftSuperBuiltUp: 950,
    sqftCarpet: 750,
    yearBuilt: 2019,
    parking: 1,
    furnishingStatus: 'unfurnished',
    reraNumber: 'K-RERA-1-440-2019-HP-220098',
    location: {
      address: 'Collectorate Ward, Kottayam',
      city: 'Kottayam',
      district: 'Kottayam',
      state: 'Kerala',
      pincode: '686002',
      latitude: 9.5950,
      longitude: 76.5200,
    },
    amenities: [
      { item: 'Lift' },
      { item: 'Parking' },
      { item: 'Water Supply' },
      { item: 'Security' },
    ],
    gallery: [
      { image: { url: 'https://picsum.photos/id/1043/1200/800' } },
    ],
  },
  {
    id: '6',
    slug: 'duplex-house-erattupetta',
    title: 'Spacious Duplex House in Erattupetta',
    description: 'Well-designed duplex with separate floors for privacy. Modern kitchen, spacious bedrooms, and balconies with mountain views. Quiet residential area with good neighborhood. Suitable for joint families or rental income.',
    price: 7800000,
    priceLabel: '₹78 Lakhs',
    type: 'duplex',
    status: 'available',
    featured: false,
    bedrooms: 4,
    bathrooms: 4,
    sqftSuperBuiltUp: 2200,
    sqftCarpet: 1800,
    yearBuilt: 2022,
    parking: 2,
    furnishingStatus: 'semi-furnished',
    reraNumber: 'K-RERA-1-440-2022-HP-220167',
    location: {
      address: 'Erattupetta - Mundakayam Road',
      city: 'Erattupetta',
      district: 'Kottayam',
      state: 'Kerala',
      pincode: '686122',
      latitude: 9.6900,
      longitude: 76.7800,
    },
    amenities: [
      { item: 'Separate Entrances' },
      { item: 'Balconies' },
      { item: 'Parking' },
      { item: 'Bore Well' },
    ],
    gallery: [
      { image: { url: 'https://picsum.photos/id/1047/1200/800' } },
    ],
  },
];

export const mockLands = [
  {
    id: '1',
    slug: 'residential-plot-pala-town',
    title: '15 Cent Residential Plot in Pala Town',
    description: 'Prime residential plot in the heart of Pala town. Clear title with proper documentation. Excellent location near schools, hospitals, and markets. Ideal for building your dream home. Road frontage with all utilities available.',
    price: 4500000,
    priceLabel: '₹45 Lakhs',
    status: 'available',
    featured: true,
    totalArea: 6534, // 15 cents in sq.ft
    pricePerCent: 300000,
    cents: 15,
    location: {
      address: 'Pala Town, Near Bishop House',
      city: 'Pala',
      district: 'Kottayam',
      state: 'Kerala',
      pincode: '686575',
    },
    gallery: [
      { image: { url: 'https://picsum.photos/id/1051/1200/800' } },
    ],
  },
  {
    id: '2',
    slug: 'rubber-plantation-erattupetta',
    title: '1 Acre Rubber Plantation near Erattupetta',
    description: 'Productive rubber plantation with mature trees. Regular tapping income. Good access road and water source available. Peaceful location with scenic views. Perfect for agricultural investment or weekend retreat.',
    price: 8000000,
    priceLabel: '₹80 Lakhs',
    status: 'available',
    featured: true,
    totalArea: 43560, // 1 acre in sq.ft
    pricePerCent: 200000,
    cents: 100,
    location: {
      address: 'Erattupetta - Pala Road',
      city: 'Erattupetta',
      district: 'Kottayam',
      state: 'Kerala',
      pincode: '686121',
    },
    gallery: [
      { image: { url: 'https://picsum.photos/id/1053/1200/800' } },
    ],
  },
  {
    id: '3',
    slug: 'commercial-plot-mc-road',
    title: '25 Cent Commercial Plot on MC Road',
    description: 'Premium commercial plot on busy MC Road, Kottayam. High visibility location with heavy traffic. Suitable for showroom, office complex, or commercial building. Clear title with all approvals. Excellent investment opportunity.',
    price: 25000000,
    priceLabel: '₹2.5 Cr',
    status: 'available',
    featured: true,
    totalArea: 10890, // 25 cents in sq.ft
    pricePerCent: 1000000,
    cents: 25,
    location: {
      address: 'MC Road, Kottayam',
      city: 'Kottayam',
      district: 'Kottayam',
      state: 'Kerala',
      pincode: '686001',
    },
    gallery: [
      { image: { url: 'https://picsum.photos/id/1055/1200/800' } },
    ],
  },
];

export const mockProjects = [
  {
    id: '1',
    slug: 'green-meadows-pala',
    title: 'Green Meadows Residential Project',
    description: 'Premium gated community project in Pala with 45 villa plots and 30 apartments. Modern amenities including clubhouse, children\'s play area, and landscaped gardens. RERA approved project with transparent pricing and timely delivery guarantee.',
    status: 'ongoing',
    featured: true,
    totalUnits: 75,
    availableUnits: 28,
    completionDate: '2025-12-31',
    reraNumber: 'K-RERA-1-440-2024-PR-220245',
    location: {
      address: 'Pala Bypass Road',
      city: 'Pala',
      district: 'Kottayam',
      state: 'Kerala',
      pincode: '686575',
    },
    amenities: [
      { item: 'Clubhouse' },
      { item: 'Children Play Area' },
      { item: 'Landscaped Gardens' },
      { item: '24/7 Security' },
      { item: 'Power Backup' },
      { item: 'Rainwater Harvesting' },
    ],
    gallery: [
      { image: { url: 'https://picsum.photos/id/1061/1200/800' } },
      { image: { url: 'https://picsum.photos/id/1062/1200/800' } },
    ],
  },
  {
    id: '2',
    slug: 'skyline-towers-kottayam',
    title: 'Skyline Towers - Luxury Apartments',
    description: 'High-rise luxury apartment complex in Kottayam city. Premium 2BHK and 3BHK apartments with modern amenities. Strategic location with excellent connectivity. Smart home features and eco-friendly design.',
    status: 'upcoming',
    featured: true,
    totalUnits: 96,
    availableUnits: 96,
    completionDate: '2026-06-30',
    reraNumber: 'K-RERA-1-440-2025-PR-220267',
    location: {
      address: 'MC Road, Near Medical College',
      city: 'Kottayam',
      district: 'Kottayam',
      state: 'Kerala',
      pincode: '686008',
    },
    amenities: [
      { item: 'Swimming Pool' },
      { item: 'Gym & Spa' },
      { item: 'Rooftop Garden' },
      { item: 'Lift' },
      { item: 'Covered Parking' },
      { item: 'Solar Power' },
    ],
    gallery: [
      { image: { url: 'https://picsum.photos/id/1064/1200/800' } },
    ],
  },
  {
    id: '3',
    slug: 'heritage-villas-erattupetta',
    title: 'Heritage Villas - Traditional Homes',
    description: 'Exclusive villa project combining traditional Kerala architecture with modern amenities. 20 premium villas in serene location. Each villa designed with traditional elements like nalukettu style, wooden work, and courtyards.',
    status: 'ongoing',
    featured: true,
    totalUnits: 20,
    availableUnits: 7,
    completionDate: '2025-09-30',
    reraNumber: 'K-RERA-1-440-2024-PR-220234',
    location: {
      address: 'Erattupetta - Mundakayam Road',
      city: 'Erattupetta',
      district: 'Kottayam',
      state: 'Kerala',
      pincode: '686121',
    },
    amenities: [
      { item: 'Traditional Architecture' },
      { item: 'Wooden Interiors' },
      { item: 'Private Gardens' },
      { item: 'Gated Community' },
      { item: 'Security' },
      { item: 'Eco-Friendly Design' },
    ],
    gallery: [
      { image: { url: 'https://picsum.photos/id/1067/1200/800' } },
    ],
  },
];
