// Mock data for the site

export const mockProperties = [
  {
    id: '1',
    slug: 'luxury-villa-whitefield',
    title: 'Luxury Villa in Whitefield',
    description: 'Stunning 4BHK villa with modern amenities, private pool, and landscaped garden. Perfect for families looking for spacious living in a prime location.',
    price: 35000000,
    priceLabel: '₹3.5 Cr',
    type: 'villa',
    status: 'available',
    featured: true,
    bedrooms: 4,
    bathrooms: 5,
    sqftSuperBuiltUp: 3500,
    sqftCarpet: 2800,
    yearBuilt: 2023,
    parking: 2,
    furnishingStatus: 'semi-furnished',
    location: {
      address: 'Whitefield Main Road',
      city: 'Bangalore',
      state: 'Karnataka',
      pincode: '560066',
      latitude: 12.9698,
      longitude: 77.7499,
    },
    amenities: [
      { item: 'Swimming Pool' },
      { item: 'Gym' },
      { item: 'Garden' },
      { item: 'Security' },
      { item: 'Power Backup' },
      { item: 'Club House' },
    ],
    gallery: [
      { image: { url: 'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=1200' } },
      { image: { url: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1200' } },
      { image: { url: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=1200' } },
    ],
  },
  {
    id: '2',
    slug: 'modern-apartment-koramangala',
    title: 'Modern 3BHK Apartment in Koramangala',
    description: 'Contemporary apartment with premium finishes, smart home features, and excellent connectivity. Located in the heart of Bangalore\'s tech hub.',
    price: 18500000,
    priceLabel: '₹1.85 Cr',
    type: 'apartment',
    status: 'available',
    featured: true,
    bedrooms: 3,
    bathrooms: 3,
    sqftSuperBuiltUp: 1850,
    sqftCarpet: 1450,
    yearBuilt: 2024,
    parking: 2,
    furnishingStatus: 'fully-furnished',
    location: {
      address: '80 Feet Road, Koramangala',
      city: 'Bangalore',
      state: 'Karnataka',
      pincode: '560095',
      latitude: 12.9352,
      longitude: 77.6245,
    },
    amenities: [
      { item: 'Gym' },
      { item: 'Parking' },
      { item: 'Security' },
      { item: 'Power Backup' },
      { item: 'Elevator' },
      { item: 'Intercom' },
    ],
    gallery: [
      { image: { url: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=1200' } },
      { image: { url: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=1200' } },
    ],
  },
  {
    id: '3',
    slug: 'penthouse-indiranagar',
    title: 'Exclusive Penthouse in Indiranagar',
    description: 'Luxurious penthouse with panoramic city views, private terrace, and world-class amenities. The epitome of urban luxury living.',
    price: 45000000,
    priceLabel: '₹4.5 Cr',
    type: 'penthouse',
    status: 'available',
    featured: true,
    bedrooms: 4,
    bathrooms: 5,
    sqftSuperBuiltUp: 4200,
    sqftCarpet: 3500,
    yearBuilt: 2024,
    parking: 3,
    furnishingStatus: 'fully-furnished',
    location: {
      address: '100 Feet Road, Indiranagar',
      city: 'Bangalore',
      state: 'Karnataka',
      pincode: '560038',
      latitude: 12.9716,
      longitude: 77.6412,
    },
    amenities: [
      { item: 'Private Terrace' },
      { item: 'Jacuzzi' },
      { item: 'Home Theater' },
      { item: 'Gym' },
      { item: 'Concierge Service' },
      { item: 'Valet Parking' },
    ],
    gallery: [
      { image: { url: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=1200' } },
      { image: { url: 'https://images.unsplash.com/photo-1600607687644-c7171b42498b?w=1200' } },
    ],
  },
  {
    id: '4',
    slug: 'villa-sarjapur-road',
    title: 'Spacious Villa on Sarjapur Road',
    description: 'Beautiful 5BHK villa with large garden, modern kitchen, and premium fixtures. Ideal for large families seeking comfort and space.',
    price: 28000000,
    priceLabel: '₹2.8 Cr',
    type: 'villa',
    status: 'available',
    featured: false,
    bedrooms: 5,
    bathrooms: 6,
    sqftSuperBuiltUp: 4000,
    sqftCarpet: 3200,
    yearBuilt: 2023,
    parking: 3,
    furnishingStatus: 'semi-furnished',
    location: {
      address: 'Sarjapur Road',
      city: 'Bangalore',
      state: 'Karnataka',
      pincode: '560035',
      latitude: 12.9121,
      longitude: 77.6846,
    },
    amenities: [
      { item: 'Garden' },
      { item: 'Security' },
      { item: 'Power Backup' },
      { item: 'Parking' },
    ],
    gallery: [
      { image: { url: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1200' } },
    ],
  },
  {
    id: '5',
    slug: 'apartment-hsr-layout',
    title: '2BHK Apartment in HSR Layout',
    description: 'Cozy apartment perfect for young professionals and small families. Well-connected to IT parks and shopping centers.',
    price: 12500000,
    priceLabel: '₹1.25 Cr',
    type: 'apartment',
    status: 'available',
    featured: false,
    bedrooms: 2,
    bathrooms: 2,
    sqftSuperBuiltUp: 1200,
    sqftCarpet: 950,
    yearBuilt: 2022,
    parking: 1,
    furnishingStatus: 'semi-furnished',
    location: {
      address: 'Sector 2, HSR Layout',
      city: 'Bangalore',
      state: 'Karnataka',
      pincode: '560102',
      latitude: 12.9121,
      longitude: 77.6446,
    },
    amenities: [
      { item: 'Gym' },
      { item: 'Parking' },
      { item: 'Security' },
      { item: 'Elevator' },
    ],
    gallery: [
      { image: { url: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=1200' } },
    ],
  },
  {
    id: '6',
    slug: 'duplex-jp-nagar',
    title: 'Elegant Duplex in JP Nagar',
    description: 'Stylish duplex with contemporary design, spacious rooms, and excellent natural lighting. Perfect blend of comfort and luxury.',
    price: 22000000,
    priceLabel: '₹2.2 Cr',
    type: 'duplex',
    status: 'available',
    featured: false,
    bedrooms: 4,
    bathrooms: 4,
    sqftSuperBuiltUp: 2800,
    sqftCarpet: 2200,
    yearBuilt: 2023,
    parking: 2,
    furnishingStatus: 'semi-furnished',
    location: {
      address: '7th Phase, JP Nagar',
      city: 'Bangalore',
      state: 'Karnataka',
      pincode: '560078',
      latitude: 12.9081,
      longitude: 77.5831,
    },
    amenities: [
      { item: 'Parking' },
      { item: 'Security' },
      { item: 'Power Backup' },
      { item: 'Garden' },
    ],
    gallery: [
      { image: { url: 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=1200' } },
    ],
  },
];

export const mockLands = [
  {
    id: '1',
    slug: 'premium-plot-devanahalli',
    title: 'Premium Plot near Devanahalli Airport',
    description: 'DTCP approved plot with clear title, excellent investment opportunity near the upcoming airport city. Perfect for building your dream home or investment.',
    price: 8500000,
    priceLabel: '₹85 Lakhs',
    status: 'available',
    featured: true,
    totalArea: 2400,
    location: {
      address: 'Devanahalli',
      city: 'Bangalore',
      state: 'Karnataka',
      pincode: '562110',
    },
    gallery: [
      { image: { url: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=1200' } },
    ],
  },
  {
    id: '2',
    slug: 'residential-plot-hennur',
    title: 'Residential Plot in Hennur',
    description: 'Well-located plot in developing area with good connectivity. Ideal for residential construction with all amenities nearby.',
    price: 6500000,
    priceLabel: '₹65 Lakhs',
    status: 'available',
    featured: true,
    totalArea: 1800,
    location: {
      address: 'Hennur Main Road',
      city: 'Bangalore',
      state: 'Karnataka',
      pincode: '560043',
    },
    gallery: [
      { image: { url: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=1200' } },
    ],
  },
  {
    id: '3',
    slug: 'farmland-kanakapura',
    title: 'Agricultural Land in Kanakapura',
    description: 'Spacious agricultural land perfect for farming or weekend getaway. Peaceful location with water source and road access.',
    price: 12000000,
    priceLabel: '₹1.2 Cr',
    status: 'available',
    featured: true,
    totalArea: 5000,
    location: {
      address: 'Kanakapura Road',
      city: 'Bangalore',
      state: 'Karnataka',
      pincode: '560062',
    },
    gallery: [
      { image: { url: 'https://images.unsplash.com/photo-1625246333195-78d9c38ad449?w=1200' } },
    ],
  },
];

export const mockProjects = [
  {
    id: '1',
    slug: 'green-valley-residency',
    title: 'Green Valley Residency',
    description: 'Premium gated community with 200+ villas and apartments. World-class amenities including clubhouse, swimming pool, sports facilities, and landscaped gardens.',
    status: 'ongoing',
    featured: true,
    totalUnits: 250,
    availableUnits: 45,
    completionDate: '2025-12-31',
    location: {
      address: 'Electronic City Phase 2',
      city: 'Bangalore',
      state: 'Karnataka',
      pincode: '560100',
    },
    amenities: [
      { item: 'Clubhouse' },
      { item: 'Swimming Pool' },
      { item: 'Gym' },
      { item: 'Sports Complex' },
      { item: 'Children Play Area' },
      { item: '24/7 Security' },
    ],
    gallery: [
      { image: { url: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=1200' } },
      { image: { url: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=1200' } },
    ],
  },
  {
    id: '2',
    slug: 'skyline-towers',
    title: 'Skyline Towers',
    description: 'Luxury high-rise apartments with stunning city views. Modern architecture with smart home features and premium amenities.',
    status: 'upcoming',
    featured: true,
    totalUnits: 180,
    availableUnits: 180,
    completionDate: '2026-06-30',
    location: {
      address: 'MG Road',
      city: 'Bangalore',
      state: 'Karnataka',
      pincode: '560001',
    },
    amenities: [
      { item: 'Infinity Pool' },
      { item: 'Sky Lounge' },
      { item: 'Gym & Spa' },
      { item: 'Concierge Service' },
      { item: 'Valet Parking' },
    ],
    gallery: [
      { image: { url: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=1200' } },
    ],
  },
  {
    id: '3',
    slug: 'serene-gardens',
    title: 'Serene Gardens',
    description: 'Eco-friendly residential project with focus on sustainability. Solar power, rainwater harvesting, and organic gardens.',
    status: 'ongoing',
    featured: true,
    totalUnits: 120,
    availableUnits: 30,
    completionDate: '2025-09-30',
    location: {
      address: 'Sarjapur Road',
      city: 'Bangalore',
      state: 'Karnataka',
      pincode: '560035',
    },
    amenities: [
      { item: 'Organic Garden' },
      { item: 'Solar Power' },
      { item: 'Rainwater Harvesting' },
      { item: 'Jogging Track' },
      { item: 'Yoga Center' },
    ],
    gallery: [
      { image: { url: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1200' } },
    ],
  },
];
